apiVersion: v1
kind: PersistentVolume
metadata:
  name: similar-word
  namespace: similar-word
spec:
  storageClassName: "example-storageclass"
  capacity:
    storage: 40G
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: similar-word
    namespace: similar-word
  gcePersistentDisk:
    pdName: similar-word
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: similar-word
  namespace: similar-word
spec:
  storageClassName: "example-storageclass"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40G
