using System;
static class Constants
{
    public static readonly string[] cocoLabelEN = {
            "person",
            "bicycle",
            "car",
            "motorbike",
            "aeroplane",
            "bus",
            "train",
            "truck",
            "boat",
            "traffic light",
            "fire hydrant",
            "stop sign",
            "parking meter",
            "bench",
            "bird",
            "cat",
            "dog",
            "horse",
            "sheep",
            "cow",
            "elephant",
            "bear",
            "zebra",
            "giraffe",
            "backpack",
            "umbrella",
            "handbag",
            "tie",
            "suitcase",
            "frisbee",
            "skis",
            "snowboard",
            "sports ball",
            "kite",
            "baseball bat",
            "baseball glove",
            "skateboard",
            "surfboard",
            "tennis racket",
            "bottle",
            "wine glass",
            "cup",
            "fork",
            "knife",
            "spoon",
            "bowl",
            "banana",
            "apple",
            "sandwich",
            "orange",
            "broccoli",
            "carrot",
            "hot dog",
            "pizza",
            "donut",
            "cake",
            "chair",
            "sofa",
            "pottedplant",
            "bed",
            "diningtable",
            "toilet",
            "tvmonitor",
            "laptop",
            "mouse",
            "remote",
            "keyboard",
            "cell phone",
            "microwave",
            "oven",
            "toaster",
            "sink",
            "refrigerator",
            "book",
            "clock",
            "vase",
            "scissors",
            "teddy bear",
            "hair drier",
            "toothbrush"
        };

    public static readonly string[] cocoLabelJP = {
            "人間",
            "自転車",
            "自動車",
            "バイク",
            "飛行機",
            "バス",
            "電車",
            "トラック",
            "ボート",
            "信号機",
            "消火栓",
            "止まれ",
            "パーキングメーター",
            "ベンチ",
            "鳥",
            "猫",
            "犬",
            "馬",
            "羊",
            "牛",
            "象",
            "熊",
            "シマウマ",
            "キリン",
            "リュックサック",
            "傘",
            "バッグ",
            "ネクタイ",
            "スーツケース",
            "フリスビー",
            "スキー",
            "スノーボード",
            "ボール",
            "タコ",
            "バット",
            "グローブ",
            "スケートボード",
            "サーフィン",
            "ラケット",
            "ボトル",
            "グラス",
            "コップ",
            "フォーク",
            "ナイフ",
            "スプーン",
            "ボウル",
            "バナナ",
            "りんご",
            "サンドイッチ",
            "オレンジ",
            "ブロッコリー",
            "人参",
            "ホットドッグ",
            "ピザ",
            "ドーナツ",
            "ケーキ",
            "椅子",
            "ソファー",
            "草木",
            "ベッド",
            "テーブル",
            "トイレ",
            "テレビ",
            "パソコン",
            "マウス",
            "リモート",
            "キーボード",
            "携帯電話",
            "電子レンジ",
            "オーブン",
            "トースター",
            "流し台",
            "冷蔵庫",
            "本",
            "時計",
            "花瓶",
            "ハサミ",
            "クマ",
            "ドライヤー",
            "歯ブラシ"
        };
}
